name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm ci

    - name: Build for production
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        GITHUB_TOKEN: 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
        BRANCH: gh-pages
        FOLDER: dist
